import Head from "next/head";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import StepsRow from "../../components/StepsRow";
import BlackButton from "../../components/ui/BlackButton";
import { ChevronLeftIcon } from "@heroicons/react/outline";
import Link from "next/link";

export default function Contact() {
  const router = useRouter();

  const {
    handleSubmit,
    formState: { errors },
  } = useForm();
  const onSubmit = (data) => {
    console.log(data);
    console.log(errors);
    if (!errors.length) {
      router.push("/contact/step-four");
    }
  };

  return (
    <div className="bg-black h-screen">
      <Head>
        <title>Contact | Crombie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        <meta name="theme-color" content="#000000" />
      </Head>

      <div className="px-8 pt-20">
        <p className="text-[11px] text-[#777] pb-5">
          What do you need from us?{" "}
        </p>

        <form
          action=""
          className="text-[11px]"
          autoComplete="off"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="mb-6 ">
            <p className=" text-white text-xl font-bold mb-2">
              I&apos;m looking to
            </p>

            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              Create a project from scratch.
            </label>
            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              Continue / improve an existing project.
            </label>
            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              Hire Consultancy Services.
            </label>
            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              Just need cost/time estimate guidance
            </label>
          </div>

          <div className="mb-6 ">
            <p className=" text-white text-xl font-bold mb-2">I want to hire</p>

            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              Custom Web Development Product
            </label>
            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              Custom Mobile Development Product
            </label>
            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              CMS/E-Commerce
            </label>
            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              A team for Staff Augmentation
            </label>
            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              I don&apos;t know
            </label>
          </div>

          <div className="mb-6 ">
            <p className=" text-white text-xl font-bold mb-2">I already have</p>

            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              A detailed brief to share.
            </label>
            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              I only have an idea and would like some help with it.
            </label>
            <label className="text-white text-[9px] flex items-center mb-2">
              <input
                className="form-check-input appearance-none transition-all h-3 w-3 border border-[#777] rounded-sm bg-black checked:bg-white checked:border-white focus:outline-none duration-200 bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                type="checkbox"
                value=""
                id="flexCheckDefault"
              />
              I don&apos;t have anything
            </label>

            <div className="overflow-hidden relative transform mt-4 w-1/2 flex justify-start items-start">
              <button className="bg-indigo hover:bg-indigo-dark text-white text-[9px] border-white rounded-sm border-[1px] py-1 px-4 inline-flex items-center">
                <p className="">Attach your brief</p>
              </button>
              <input
                className="cursor-pointer absolute block opacity-0 pin-r pin-t"
                type="file"
                name="vacancyImageFiles"
              />
            </div>

          </div>

          <div className="flex items-center justify-between">
            <StepsRow step={3} />
            <div className="flex items-center">
              <Link href={"/contact/step-two"} passHref>
                <ChevronLeftIcon className="w-4 h-4 mr-2 p-[1px] rounded-full border-[#777] border-[1px] text-[#777] " />
              </Link>
              <BlackButton text="Next" type="white" />
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
