import Head from "next/head";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import StepsRow from "../../components/StepsRow";
import BlackButton from "../../components/ui/BlackButton";
import { ChevronLeftIcon } from "@heroicons/react/outline";
import Link from "next/link";

export default function Contact() {
  const router = useRouter();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();
  const onSubmit = (data) => {
    console.log(data);
    console.log(errors);
    if (!errors.length) {
      router.push("/contact/step-three");
    }
  };

  return (
    <div className="bg-black h-screen">
      <Head>
        <title>Contact | Crombie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        <meta name="theme-color" content="#000000" />
      </Head>

      <div className="px-8 pt-20">
        <p className="text-[11px] text-[#777] pb-5">
          Now, tell us more about your project:{" "}
        </p>

        <form
          action=""
          className="text-[11px]"
          autoComplete="off"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="mb-4 ">
            <label className=" text-white font-bold mb-2">My name is</label>
            <input
              {...register("nameP", {
                required: true,
              })}
              type="text"
              placeholder="Your project name"
              className={`${
                errors.nameP
                  ? "focus:border-b-red-800 "
                  : "focus:border-b-[#282826]"
              } w-full py-1 pr-3 leading-tight focus:outline-none  focus:border-b-[1px] bg-black text-[#777] placeholder:text-[11px] placeholder:text-[#282826] `}
            />
            <div className="text-red-800 text-[10px]  ">
              {errors.nameP?.type === "required" &&
                "A project name is required"}
            </div>
          </div>

          <div className="mb-4 ">
            <label className=" text-white font-bold mb-2">Our goal is</label>
            <textarea
              {...register("goal")}
              rows="5"
              type="text"
              placeholder="Your goals"
              className={
                "w-full py-1 pr-3 leading-tight focus:outline-none  focus:border-b-[1px] bg-black text-[#777] placeholder:text-[11px] placeholder:text-[#282826] "
              }
            />
          </div>

          <div className="flex items-center justify-between">
            <StepsRow step={2} />
            <div className="flex items-center">
              <Link href={"/contact/step-one"} passHref>
                <ChevronLeftIcon className="w-4 h-4 mr-2 p-[1px] rounded-full border-[#777] border-[1px] text-[#777] " />
              </Link>
              <BlackButton text="Next" type="white" />
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
