import Head from "next/head";
import ErrorHeader from "../components/ErrorHeader";
import Footer from "../components/Footer";

export default function Custom404() {
  return (
    <div className="bg-black h-screen">
      <Head>
        <title>Error 404 | Crombie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        <meta name="theme-color" content="#000000" />
      </Head>

      <ErrorHeader />
      <div className="text-white">
        <Footer />
      </div>
    </div>
  );
}
