import Head from "next/head";
import ErrorHeader from "../components/ErrorHeader";
import Navbar from "../components/Navbar";

export default function Custom404() {
  return (
    <div className="bg-black h-screen">
      <Head>
        <title>Crombie | Error 404 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        <meta name="theme-color" content="#000000" />
      </Head>

      <Navbar />
      <ErrorHeader />
    </div>
  );
}
