import Head from "next/head";
import BottomOverlay from "../components/BottomOverlay";
import PageHeader from "../components/PageHeader";
import DisclosureComp from "../components/ui/DisclosureComp";
import TesimonialCarousel from "../components/ui/TesimonialCarousel";

export default function Culture() {
  return (
    <div className="bg-black h-screen text-white">
      <Head>
        <title>Culture | Crombie </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        <meta name="theme-color" content="#000000" />
      </Head>

      <PageHeader page="culture" />
      <DisclosureComp />

      <div className="bg-black">
        <div className="py-5 border-b-[.5px] border-[#f36] mb-4 ">
          <div className="px-8 text-xs font-bold leading-4">
            <p>
              What’s Crombie <br />
              for its people?
            </p>
          </div>
        </div>
        <TesimonialCarousel/>
      </div>
     

      <BottomOverlay />
    </div>
  );
}
