import Head from "next/head";
import BottomOverlay from "../components/BottomOverlay"
import PageHeader from "../components/PageHeader";
import DisclosureComp from "../components/UI/Disclosure";

export default function Culture() {
  return (
    <div className="bg-black h-screen text-white">
      <Head>
        <title>Culture | Crombie </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        <meta name="theme-color" content="#000000" />
      </Head>

      <PageHeader page="culture" />
      <DisclosureComp />

      <BottomOverlay />

    </div>
  );
}
