import Head from "next/head";
import HomeHeader from "../components/HomeHeader";
import Navbar from "../components/Navbar";
import Services from "../components/Services";
import Study from "../components/Study";
import BottomOverlay from "../components/BottomOverlay"

export default function Home() {
  return (
    <div className="bg-black h-screen text-white">
      <Head>
        <title>Crombie | Dev (Clone) </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <Navbar />
      <HomeHeader />
      <Services />
      <Study />

      <BottomOverlay />

    </div>
  );
}
