/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useState } from "react";
import BlackButton from "../components/ui/BlackButton";
import { motion, AnimatePresence } from "framer-motion";
import Image from "next/image";
import Head from "next/head";

export default function Work() {
  const [work, setWork] = useState("Flopster");
  const [info, setInfo] = useState({});

  useEffect(() => {
    switch (work) {
      case "Flopster":
        setInfo({
          title: "Flopster: UX/UI Design, Mobile & Back-End Development",
          desc: "A central platform that helps build and grow a community of local pet lovers, right on your door step.",
          src: "_nuxt/img/93aa32b.png",
        });
        break;
      case "Lazo":
        setInfo({
          title: "Lazo: UX/UI Design, Mobile & Back-End Development",
          desc: "An app made to encourage neighbours to participate and collaborate with the community.",
          src: "_nuxt/img/e4e90c8.png",
        });
        break;
      case "GP":
        setInfo({
          title: "GP Stats: UX/UI Design, Mobile & Back-End Development",
          desc: "Mobile App for golfers that tracks their game with data and stats to improve their performance.",
          src: "_nuxt/img/6d23605.png",
        });
        break;
      case "Proode":
        setInfo({
          title: "Proode: UX/UI Design, Mobile & Back-End Development",
          desc: "A web and mobile plataform for a widely spread soccer betting game in Argentina.",
          src: "_nuxt/img/3f56fa0.png",
        });
        break;
      case "Serenisima":
        setInfo({
          title: "La serenisima: UX/UI Design, Mobile & Back-End Development",
          desc: "An ecommerce platform for one of the largest dairy brands in Argentina.",
          src: "/_nuxt/img/395f7d4.png",
        });
        break;
      case "Hand":
        setInfo({
          title:
            "The Hand Project: UX/UI Design, Mobile & Back-End Development",
          desc: "An application where its users request and provide aid to each other.",
          src: "/_nuxt/img/8852b9c.png",
        });
        break;
      case "Link":
        setInfo({
          title: "New Link: UX/UI Design, Mobile & Back-End Development",
          desc: "A desktop and mobile platform to manage project tasks, deliveries and materials, generating better communication between executives, collaborators and clients.",
          src: "/_nuxt/img/c5a778d.png",
        });
        break;
      case "Assist":
        setInfo({
          title: "Assist Travel: UX/UI Design, Mobile & Back-End Development",
          desc: "A fundamental app for travelers that provides insurance and assistance around the world.",
          src: "/_nuxt/img/1913fd7.png",
        });
        break;
      case "Recreo":
        setInfo({
          title:
            "ReCreo: UX/UI Design, Mobile, Front and Back-End Development.",
          desc: "An app and a website with a schedule of events, information on destinations, guides.",
          src: "/_nuxt/img/bb10318.jpg",
        });
        break;
      case "SWC":
        setInfo({
          title: "SWC: Mobile Development",
          desc: "A platform that helps users to track their health.",
          src: "/_nuxt/img/10cf2d9.jpg",
        });
        break;
      case "EliPro":
        setInfo({
          title: "EliPro: UX/UI Design, React Native for Mobile, PHP Laravel.",
          desc: "EliPro is the application that accompanies health professionals during key moments.",
          src: "/_nuxt/img/ee59cbb.jpg",
        });
        break;
      default:
        setInfo({
          title: "Error",
          desc: "In fetching data",
          src: "_nuxt/img/3f56fa0.png",
        });
        break;
    }
  }, [work]);

  return (
    <>
      <Head>
        <title>Work| Crombie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        <meta name="theme-color" content="#000000" />
      </Head>

      <div className="relative w-screen h-screen">
        <div className="px-8 pb-10 pt-24 ">
          <p className="text-[#666] fixed w-2/4 z-30 text-[10px] ">
            Take a look at some of the experiences we <br /> created for
            real-world users.
          </p>

          <div className="mt-20 flex flex-col items-start ">
            <button onClick={() => setWork("Flopster")}>
              <h1
                className={`${
                  work === "Flopster" ? "text-white" : "text-[#181816]"
                } relative z-20 transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                Flopster
              </h1>
            </button>
            <button onClick={() => setWork("Lazo")}>
              <h1
                className={`${
                  work === "Lazo" ? "text-white" : "text-[#181816]"
                } relative z-10 transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                Lazo
              </h1>
            </button>
            <button onClick={() => setWork("GP")}>
              <h1
                className={`${
                  work === "GP" ? "text-white" : "text-[#181816]"
                } relative z-20 transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                GP <br /> Stats
              </h1>
            </button>
            <button onClick={() => setWork("Proode")}>
              <h1
                className={`${
                  work === "Proode" ? "text-white" : "text-[#181816]"
                } relative z-20 transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                Proode
              </h1>
            </button>
            <button onClick={() => setWork("Serenisima")}>
              <h1
                className={`${
                  work === "Serenisima" ? "text-white" : "text-[#181816]"
                } relative z-20 transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                La <br /> Serenisima
              </h1>
            </button>
            <button onClick={() => setWork("Hand")}>
              <h1
                className={`${
                  work === "Hand" ? "text-white" : "text-[#181816]"
                } relative z-20 transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                The <br /> Hand <br /> Project
              </h1>
            </button>
            <button onClick={() => setWork("Link")}>
              <h1
                className={`${
                  work === "Link" ? "text-white" : "text-[#181816]"
                } relative z-20 transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                New <br /> Link
              </h1>
            </button>
            <button onClick={() => setWork("Assist")}>
              <h1
                className={`${
                  work === "Assist" ? "text-white" : "text-[#181816]"
                } relative z-20transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                Assist <br /> Travel
              </h1>
            </button>
            <button onClick={() => setWork("Recreo")}>
              <h1
                className={`${
                  work === "Recreo" ? "text-white" : "text-[#181816]"
                } relative z-20 transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                ReCreo
              </h1>
            </button>
            <button onClick={() => setWork("SWC")}>
              <h1
                className={`${
                  work === "SWC" ? "text-white" : "text-[#181816]"
                } relative z-20 transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                SWC
              </h1>
            </button>
            <button onClick={() => setWork("EliPro")}>
              <h1
                className={`${
                  work === "EliPro" ? "text-white" : "text-[#181816]"
                } relative z-20 transition-all duration-700 text-left font-extrabold text-4xl mb-4 `}
              >
                EliPro
              </h1>
            </button>
          </div>

          <ImageComp source={info.src} />

          <div className="fixed right-10 w-36 bottom-40 z-20 text-white">
            <p className="text-[11px] text-[#666] mb-2 ">{info.title} </p>
            <p className="text-[9px] ">{info.desc} </p>
            <BlackButton text="View case study" />
          </div>
        </div>
      </div>
    </>
  );
}

export function ImageComp({ source }) {
  return (
    <div>
      <AnimatePresence>
        <motion.div
          key={source}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <div className="fixed transition-all duration-1000 top-0 w-full right-0">
            <Image
              src={`https://crombie.dev/${source}`}
              alt=""
              width="100%"
              height="80px"
              layout="responsive"
              placeholder="blur"
              blurDataURL={`https://crombie.dev/${source}`}
            />
          </div>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
